EntityFramework_MVCWeb/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using EntityFramework_MVCWeb_BusinessAccessLayer.Domain_Models;

namespace EntityFramework_MVCWeb.Models
{
    public class Doctors
    {
        //members
        private IEnumerable<Doctor_BAL> doctors;

        public IEnumerable<Doctor_BAL> DoctorsBAL
        {
            get { return doctors; }
            set { doctors = value; }
        }
        //private string _doctorName;

        //[Display(Name="Doctor Name",Description="This is the doctors name")]
        //public string DoctorName
        //{
        //    get { return _doctorName; }
        //    set { _doctorName = value; }
        //}
        //private int _doctorId;

        //[Display(Name = "Doctor Id")]
        //public int DoctorId
        //{
        //    get { return _doctorId; }
        //    set { _doctorId = value; }
        //}
        //private string _doctorCategory;

        //[Display(Name = "Category")]
        //public string DoctorCategory
        //{
        //    get { return _doctorCategory; }
        //    set { _doctorCategory = value; }
        //}
        //private long _doctorPhoneNo;

        //[Display(Name = "Contact No")]
        //public long DoctorPhoneNo
        //{
        //    get { return _doctorPhoneNo; }
        //    set { _doctorPhoneNo = value; }
        //}

        //behaviours
    }
}

EntityFramework_MVCWeb/Models/HomeScreenViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EntityFramework_MVCWeb.Models
{
    public class HomeScreenViewModel
    {
        public HomeScreenViewModel(Doctors newDoc)
        {
            this.doctors = newDoc;
        }
        public Doctors doctors
        {
            get;
            set;
        }
    }
}

EntityFramework_MVCWeb/Controllers/GenericControlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntityFramework_MVCWeb.Controllers
{
    public class GenericControlsController : Controller
    {
        //
        // GET: /GenericControls/

        public ActionResult Index()
        {
            return View();
        }

    }
}

EntityFramework_MVCWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntityFramework_MVCWeb_DataAccessLayer;
using EntityFramework_MVCWeb_BusinessAccessLayer.Contracts;
using EntityFramework_MVCWeb.Models;
using EntityFramework_MVCWeb_BusinessAccessLayer.Domain_Models;

namespace EntityFramework_MVCWeb.Controllers
{
    public class HomeController : Controller  //All controllers inherit from System.Web.MVC.Controller (abstract class)
    {
        //
        // GET: /Home/
        private IBusinessAccessLayer bl = null;
        internal HomeScreenViewModel hsVM;
        public HomeController()
        {
            //ISSUE: dependency injected. NEED IOC pattern
            bl = new EntityFramework_MVCWeb_BusinessAccessLayer.BAL();
            hsVM = new HomeScreenViewModel(new Doctors()); 
        }
        public ActionResult Index()
        {
            //Doctor doc = new Doctor();
            //IEnumerable<Doctor_BAL> doc = bl.GetAllDoctors();
            hsVM.doctors.DoctorsBAL = bl.GetAllDoctors();
            ViewBag.Title = "Home";
            return View(hsVM);
        }

        public ActionResult SearchDoctorsByField(string SearchTerm)
        {
            return null;
        }

    }
}

EntityFramework_MVCWeb/Views/Home/Index.cshtml
@{
    Layout = "~/Views/MasterPages/_LayoutOne.cshtml";    
}
@model EntityFramework_MVCWeb.Models.HomeScreenViewModel


<div class="searchBox doctors">
    @using (Html.BeginForm("SearchDoctorsByField", "Home", FormMethod.Post, new { id = "myform", }))
    {
        //ISSUE make this a partial view
        <div class="row">
            <div class="col-md-3">
                <label for="txtSearchdoctors">Find a doctor</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                @*passing a textbox value to controller without using Model*@
                <input type="text" placeholder="Search by Id,Name or Category" id="txtSearchdoctors" name="SearchTerm" />
                @*@Html.TextBox("SearchTerm", null, new { placeholder="Search by Id,Name or Categories",id="txtSearchdoctors" })*@
                <input type="submit" value="Search" />
            </div>
        </div>
    }
</div>

<div id="doctors">
    @Html.Partial("~/Views/PartialViews/_doctorsView.cshtml", Model.doctors)
</div>

EntityFramework_MVCWeb/Views/MasterPages/_LayoutOne.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/custom.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
</head>
<body>
 
    <div id="content">
          @RenderBody() 
    </div>
</body>
</html>

EntityFramework_MVCWeb/Views/PartialViews/_doctorsView.cshtml
@model EntityFramework_MVCWeb.Models.Doctors

<div class="row">
    <div class="col-md-3">
        @(Html.LabelFor(model => model.DoctorsBAL.FirstOrDefault().DoctorId))
    </div>
    <div class="col-md-3">
        @(Html.LabelFor(model => model.DoctorsBAL.FirstOrDefault().DoctorName))
    </div>
    <div class="col-md-3">
        @Html.LabelFor(model => model.DoctorsBAL.FirstOrDefault().DoctorCategory)
    </div>
    <div class="col-md-3">
        @Html.LabelFor(model => model.DoctorsBAL.FirstOrDefault().DoctorPhoneNo)
    </div>
</div>
<div class="row">
    @if (Model.DoctorsBAL != null && Model.DoctorsBAL.Count() > 0)
    {
        foreach (EntityFramework_MVCWeb_BusinessAccessLayer.Domain_Models.Doctor_BAL doctor in Model.DoctorsBAL)
        {
        <div class="col-md-3">
            @doctor.DoctorId
        </div> 
        <div class="col-md-3">
            @doctor.DoctorName
        </div> 
        <div class="col-md-3">
            @doctor.DoctorCategory
        </div> 
        <div class="col-md-3">
            @doctor.DoctorPhoneNo
        </div>          
        }
    }
    else
    {
        <div class="col-md-9">
            Sorry!, No doctor is available
        </div>
    }
</div>
<div class="row">
    @Html.Partial("~/Views/PartialViews/_pager.cshtml",Model.DoctorsBAL.FirstOrDefault())
</div>

EntityFramework_MVCWeb/Views/PartialViews/_pager.cshtml
@using EntityFramework_MVCWeb_Abstract_BusinessAccessLayer;
@model IBusinessDomainModels
<div class="row pager">
    <div class="col-md-2">
    </div>
    <div class="col-md-6">
        @Html.ActionLink("<<<","GoToFirstPage","GenericControls",null,new {id="linkBtnFirst",title="First Page"})
        @Html.ActionLink("<","GoToPreviousPage","GenericControls",null,new {id="linkBtnPrevious",title="Previous Page"})
        <label>Page No:</label>
        <input type="text" id="txtCurrentPage" value="0" title="Current page"/>
        <label>of</label>
         <input type="text" id="txtTotalPage" title="Total pages" readonly="true"/>
        @Html.ActionLink(">","GoToNextPage","GenericControls",null,new {id="linkBtnNext",title="Next Page"})
        @Html.ActionLink(">>>","GoToLastPage","GenericControls",null,new {id="linkBtnLast",title="Last Page"})
    </div>
    <div class="col-md-3">
    </div>
</div>